apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-installation.yaml
  - sealed-secret.yaml # created by `make seal-secrets` based on your actual secret.yaml files that should NOT be checked in.
