# Add the actual values and rename this file to secret.yaml
# Then you can run `make seal-secrets` in your terminal to encrypt the secret automatically
apiVersion: v1
kind: Secret
metadata:
  name: ngrok-ingress-controller-credentials
type: Opaque
data:
  API_KEY: # base 64 encoded NGROK API_KEY
  AUTHTOKEN: # base 64 encoded NGROK AUTHTOKEN
