apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ngrok-ingress
  namespace: flux-system
spec:
  targetNamespace: ngrok-ingress-controller
  path: ./applications/ngrok-ingress-controller
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
